on: [push, pull_request]
name: Test

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.0'

      - name: Setup config.yml
        run: cp config/config.example.yml config/config.yml

      - name: Migrate
        run: make db-up

      - name: Test
        run: make test
